### ISSUE TITLE
Caps Lock Issue

### ISSUE THREAD

**Issue by dexinthecity** [David-Else/fedora-ultimate-setup-script#1]
Does this script disable the caps lock key? I've noticed that it works during login but after that it stops working all together.

**Comment by David-Else** [comment]
It makes the caps lock into a delete for touch typing purposes, the line that does it is:
https://github.com/David-Else/fedora-ultimate-setup-script/blob/e160dd36ec708e8eebf92568937024f1cfe6726e/fedora-ultimate-setup-script.sh#L358
You can delete the `'caps:backspace', ` to rectify the situation. If you want to change the current settings I assume you can just set it back to `caps` running the modified line in the terminal.

I have added an FAQ section to the readme with this information.
