### ISSUE TITLE
Snap packages repository

### ISSUE THREAD

**Issue by CSRedRat** [David-Else/fedora-ultimate-setup-script#5]
Hi! Please add Snap repository to script:

- [https://snapcraft.io/docs/installing-snap-on-fedora](https://snapcraft.io/docs/installing-snap-on-fedora)
- [https://snapcraft.io/docs/installing-snap-on-centos](https://snapcraft.io/docs/installing-snap-on-centos)
- https://snapcraft.io/snap-store

**Comment by David-Else** [comment]
Thanks for the input, but I chose Flatpak over snap. It is much better supported by Fedora and Centos.
